global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 20.0
  static_map: true
  width: 100.0
  height: 100.0
  plugins:
            -  { name: inflation_layer, type: "costmap_2d::InflationLayer", output: "screen"}
            -  { name: obstacle_layer, type: "costmap_2d::ObstacleLayer", output: "screen"}
            
 
  
#global_costmap:
   #global_frame:      map
   #robot_base_frame:  robot_footprint
   #update_frequency:  15.0 #10.0
   #publish_frequency: 15.0 #10.0
   #width:             20.0 #50.0
   #height:            20.0 #50.0
   #resolution:        0.05 #0.02
   #static_map:        true
   #rolling_window:    false
